@SimpleBettingExchange.Api_HostAddress = http://localhost:5163

GET {{SimpleBettingExchange.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5163/api/markets
Content-Type: application/json

{
  "name": "marché 1",
  "lines": [
    {
      "name": "over 1.5"
    },
    {
      "name": "under 1.5"
    }
  ]
}

###

PUT http://localhost:5163/api/markets/946484bf-3746-46a6-a7d5-5a39dcb408d2
Content-Type: application/json

{
  "name": "marché UHU"
}