@SimpleBettingExchange.Api_HostAddress = http://localhost:5163

GET {{SimpleBettingExchange.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5163/api/markets
Content-Type: application/json

{
  "name": "marché 1",
  "lines": [
    {
      "name": "over 1.5"
    },
    {
      "name": "under 1.5"
    }
  ]
}

###

PUT http://localhost:5163/api/markets/fd098611-07d3-4689-bafe-2a3d0de09136
Content-Type: application/json

{
  "name": "marché UHU"
}