@Api_HostAddress=https://localhost:7232
@MarketId=01920e7d-cdf6-42b8-8a5c-fb38f20b6d80
@SelectionId=8ed7cb2f-005d-4250-aa00-f36a37e524dd
@OrderId=01920e8d-8f78-49fd-8c56-0575c68f3c96

GET {{Api_HostAddress}}/api/orders/{{OrderId}}
Accept: application/json

###

POST {{Api_HostAddress}}/api/orders/place
Content-Type: application/json

{
    "marketId": "{{MarketId}}", 
    "traderId": "A266CE9E-19C8-43EF-992B-72FD9A68E3CC", 
    "selectionId": "{{SelectionId}}",
    "orderType": "Back", 
    "price": 2.5, 
    "size": 100.0
}

###

POST {{Api_HostAddress}}/api/orders/{{OrderId}}/match
Content-Type: application/json

{
    "orderId": "{{OrderId}}"
}

###

POST {{Api_HostAddress}}/api/orders/{{OrderId}}/settle
Content-Type: application/json

{
    "orderId": "{{OrderId}}"
}