POST http://localhost:5163/api/markets
Content-Type: application/json

{
  "Name":  "Test-668",
  "StartTime": "2025-05-27T11:00:00+02:00"
}

### GET request to example server
GET http://localhost:5163/api/markets

### GET request to example server
GET http://localhost:5163/api/markets/d3fb70c5-f976-43f0-8def-b6341732812a