### Create Market

POST http://localhost:5163/api/markets
Content-Type: application/json

{
  "EventName": "Match PSG vs OM",
  "Name":  "Issue du match",
  "StartTime": "2025-05-27T18:00:00+02:00"
}

### GET Market details
GET http://localhost:5163/api/markets/a0b0ce79-de44-4fa0-b996-2d717fc78548

### Post change market name

PUT http://localhost:5163/api/markets/d8480325-f625-46a0-a960-99891e0bfd38
Content-Type: application/json

{
  "Name":  "Un nom encore plus pourri"
}

### Add runners to market

POST http://localhost:5163/api/markets/a0b0ce79-de44-4fa0-b996-2d717fc78548/runners
Content-Type: application/json

{
  "Runners": [
    {
      "Name": "Victoire PSG",
      "BackPrice": {
        "Price": "1.5",
        "Size": "100"
      },
      "LayPrice": {
        "Price": "8.5",
        "Size": "100"
      }
    },
    {
      "Name": "Match nul",
      "BackPrice": {
        "Price": "3.0",
        "Size": "100"
      },
      "LayPrice": {
        "Price": "3.5",
        "Size": "100"
      }
    },
    {
      "Name": "Victoire OM",
      "BackPrice": {
        "Price": "10.0",
        "Size": "100"
      },
      "LayPrice": {
        "Price": "1.4",
        "Size": "100"
      }
    }
  ]
}