POST http://localhost:5163/api/markets
Content-Type: application/json

{
  "Name":  "Test-6733",
  "StartTime": "2025-05-27T16:00:00+02:00"
}

### GET request to example server
GET http://localhost:5163/api/markets

### GET request to example server
GET http://localhost:5163/api/markets/1b762b49-465c-4a2a-8569-7c8108033d14

### Post change market name

PUT http://localhost:5163/api/markets/1b762b49-465c-4a2a-8569-7c8108033d14
Content-Type: application/json

{
  "Name":  "Un nom encore plus pourri"
}