@Api_HostAddress=https://localhost:7232
@MarketId=019256d8-16ea-4e71-91a7-7cef9b4f08db

GET {{Api_HostAddress}}/api/markets/

###

GET {{Api_HostAddress}}/api/markets/{{MarketId}}/events

###
GET {{Api_HostAddress}}/api/markets/{{MarketId}}

###

POST {{Api_HostAddress}}/api/markets
Content-Type: application/json

{
    "name": "Match Odds PSG / OM",
    "lines": [
      { "name": "Victoire du PSG" },
      { "name": "Victoire de l'OM" },
      { "name": "Match nul" }
    ]
}

###

POST {{Api_HostAddress}}/api/markets/{{MarketId}}/open
Content-Type: application/json

{
    "marketId": "{{MarketId}}"
}

###

POST {{Api_HostAddress}}/api/markets/{{MarketId}}/suspend
Content-Type: application/json

{
    "marketId": "{{MarketId}}"
}

###

POST {{Api_HostAddress}}/api/markets/{{MarketId}}/resume
Content-Type: application/json

{
    "marketId": "{{MarketId}}"
}

###

POST {{Api_HostAddress}}/api/markets/{{MarketId}}/suspend
Content-Type: application/json

{
    "marketId": "{{MarketId}}"
}

###

POST {{Api_HostAddress}}/api/markets/{{MarketId}}/close
Content-Type: application/json

{
    "marketId": "{{MarketId}}"
}

###

POST {{Api_HostAddress}}/api/markets
Content-Type: application/json

{
    "name": "over/under 0.5 PSG / OM",
    "lines": [
      { "name": "over 0.5" },
      { "name": "under 0.5" }
    ]
}

###

POST {{Api_HostAddress}}/api/markets/019205b5-9854-416f-8205-2acbfd4a05cb/open
Content-Type: application/json

{
    "marketId": "019205b5-9854-416f-8205-2acbfd4a05cb"
}

###

POST {{Api_HostAddress}}/api/markets/019205b5-9854-416f-8205-2acbfd4a05cb/close
Content-Type: application/json

{
    "marketId": "019205b5-9854-416f-8205-2acbfd4a05cb"
}