@Api_HostAddress=http://localhost:5555/

GET http://localhost:5555/api/markets/

###

GET http://localhost:5555/api/markets/83663b95-242b-414c-a293-bbc142af0b9c/events

###

POST http://localhost:5555/api/markets
Content-Type: application/json

{
    "name": "Match Odds PSG / OM",
    "lines": [
      { "name": "Victoire du PSG" },
      { "name": "Victoire de l'OM" },
      { "name": "Match nul" }
    ]
}

###

POST http://localhost:5555/api/markets/83663b95-242b-414c-a293-bbc142af0b9c/open
Content-Type: application/json

{
    "marketId": "83663b95-242b-414c-a293-bbc142af0b9c"
}

###

POST {{Api_HostAddress}}/api/markets/01920ad2-ec59-4d1e-bbe2-db445c70ccd4/suspend
Content-Type: application/json

{
    "marketId": "01920ad2-ec59-4d1e-bbe2-db445c70ccd4"
}

###

POST {{Api_HostAddress}}/api/markets/01920ad2-ec59-4d1e-bbe2-db445c70ccd4/resume
Content-Type: application/json

{
    "marketId": "01920ad2-ec59-4d1e-bbe2-db445c70ccd4"
}

###

POST {{Api_HostAddress}}/api/markets/01920ad2-ec59-4d1e-bbe2-db445c70ccd4/suspend
Content-Type: application/json

{
    "marketId": "01920ad2-ec59-4d1e-bbe2-db445c70ccd4"
}

###

POST {{Api_HostAddress}}/api/markets/01920ad2-ec59-4d1e-bbe2-db445c70ccd4/close
Content-Type: application/json

{
    "marketId": "01920ad2-ec59-4d1e-bbe2-db445c70ccd4"
}

###

POST {{Api_HostAddress}}/api/markets
Content-Type: application/json

{
    "name": "over/under 0.5 PSG / OM",
    "lines": [
      { "name": "over 0.5" },
      { "name": "under 0.5" }
    ]
}

###

POST {{Api_HostAddress}}/api/markets/019205b5-9854-416f-8205-2acbfd4a05cb/open
Content-Type: application/json

{
    "marketId": "019205b5-9854-416f-8205-2acbfd4a05cb"
}

###

POST {{Api_HostAddress}}/api/markets/019205b5-9854-416f-8205-2acbfd4a05cb/close
Content-Type: application/json

{
    "marketId": "019205b5-9854-416f-8205-2acbfd4a05cb"
}